import { assertEquals } from '@std/assert';

import { handleUpsertAttendanceSavedView } from '../handler.ts';

const TEST_ORIGIN = 'https://app.example.com';
const EVENT_ID = '11111111-1111-4111-8111-111111111111';
const VIEW_ID = '22222222-2222-4222-8222-222222222222';
const CONFIG = { columns: ['member_id', 'full_name'], filters: [] };

async function withFunctionEnv(run: () => Promise<void>) {
  const names = ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY', 'ALLOWED_ORIGINS'];
  const previous = new Map(names.map((name) => [name, Deno.env.get(name)]));
  Deno.env.set('SUPABASE_URL', 'https://example.supabase.co');
  Deno.env.set('SUPABASE_SERVICE_ROLE_KEY', 'test-service-role-key');
  Deno.env.set('ALLOWED_ORIGINS', TEST_ORIGIN);
  try {
    await run();
  } finally {
    for (const [name, value] of previous) {
      if (value === undefined) Deno.env.delete(name);
      else Deno.env.set(name, value);
    }
  }
}

function buildRequest(body: unknown) {
  return new Request('https://example.functions/upsert-attendance-saved-view', {
    method: 'POST',
    headers: {
      origin: TEST_ORIGIN,
      'content-type': 'application/json',
      authorization: 'Bearer admin-access-token',
    },
    body: JSON.stringify(body),
  });
}

function mockFetch(options: {
  role?: string;
  count?: number | null;
  countError?: boolean;
  writeError?: { code: string; message: string };
}) {
  const originalFetch = globalThis.fetch;
  const writes: Array<{ method: string; body: unknown; url: URL }> = [];
  globalThis.fetch = (input, init) => {
    const requestUrl = new URL(input instanceof Request ? input.url : input.toString());
    if (requestUrl.pathname === '/auth/v1/user') {
      return Promise.resolve(Response.json({ id: crypto.randomUUID() }));
    }
    if (requestUrl.pathname === '/rest/v1/admins') {
      return Promise.resolve(Response.json({ id: 'admin-row', role: options.role ?? 'admin' }));
    }
    if (requestUrl.pathname === '/rest/v1/attendance_saved_views' && init?.method === 'HEAD') {
      if (options.countError) {
        return Promise.resolve(Response.json({ message: 'count failed' }, { status: 500 }));
      }
      return Promise.resolve(
        new Response(null, {
          status: 200,
          headers: { 'content-range': `0-${(options.count ?? 2) - 1}/${options.count ?? 2}` },
        }),
      );
    }
    if (requestUrl.pathname === '/rest/v1/attendance_saved_views') {
      writes.push({
        method: init?.method ?? 'GET',
        body: init?.body ? (JSON.parse(String(init.body)) as unknown) : null,
        url: requestUrl,
      });
      if (options.writeError) {
        return Promise.resolve(Response.json(options.writeError, { status: 409 }));
      }
      return Promise.resolve(
        Response.json({ id: VIEW_ID, event_id: EVENT_ID, name: 'View 3', view_config: CONFIG }),
      );
    }
    return Promise.resolve(new Response('Unexpected request', { status: 500 }));
  };
  return {
    writes,
    restore: () => {
      globalThis.fetch = originalFetch;
    },
  };
}

Deno.test('upsert-attendance-saved-view validates event, name, and config', async () => {
  await withFunctionEnv(async () => {
    const response = await handleUpsertAttendanceSavedView(
      buildRequest({ event_id: 'bad', name: '', view_config: [] }),
    );
    assertEquals(response.status, 400);
  });
});

Deno.test('upsert-attendance-saved-view creates a view with an autogenerated name', async () => {
  await withFunctionEnv(async () => {
    const fetchMock = mockFetch({ count: 2 });
    try {
      const response = await handleUpsertAttendanceSavedView(
        buildRequest({ event_id: EVENT_ID, name: 'View 1', view_config: CONFIG }),
      );
      assertEquals(response.status, 201);
      assertEquals(fetchMock.writes[0].method, 'POST');
      assertEquals(fetchMock.writes[0].body, {
        event_id: EVENT_ID,
        name: 'View 3',
        view_config: CONFIG,
      });
    } finally {
      fetchMock.restore();
    }
  });
});

Deno.test('upsert-attendance-saved-view updates named views and blocks SLOD updates', async () => {
  await withFunctionEnv(async () => {
    const fetchMock = mockFetch({});
    try {
      const response = await handleUpsertAttendanceSavedView(
        buildRequest({ id: VIEW_ID, event_id: EVENT_ID, name: 'By member', view_config: CONFIG }),
      );
      assertEquals(response.status, 200);
      assertEquals(fetchMock.writes[0].method, 'PATCH');
      const updatedView = fetchMock.writes[0].body as Record<string, unknown>;
      assertEquals(updatedView.name, 'By member');
      assertEquals(fetchMock.writes[0].url.searchParams.get('event_id'), `eq.${EVENT_ID}`);
    } finally {
      fetchMock.restore();
    }

    const slodMock = mockFetch({ role: 'slod' });
    try {
      const response = await handleUpsertAttendanceSavedView(
        buildRequest({ id: VIEW_ID, event_id: EVENT_ID, name: 'By member', view_config: CONFIG }),
      );
      assertEquals(response.status, 403);
      assertEquals(slodMock.writes, []);
    } finally {
      slodMock.restore();
    }
  });
});

Deno.test('upsert-attendance-saved-view maps duplicate-name and count failures', async () => {
  await withFunctionEnv(async () => {
    const duplicateMock = mockFetch({ writeError: { code: '23505', message: 'duplicate name' } });
    try {
      const response = await handleUpsertAttendanceSavedView(
        buildRequest({ event_id: EVENT_ID, name: 'By member', view_config: CONFIG }),
      );
      assertEquals(response.status, 409);
    } finally {
      duplicateMock.restore();
    }

    const countErrorMock = mockFetch({ countError: true });
    try {
      const response = await handleUpsertAttendanceSavedView(
        buildRequest({ event_id: EVENT_ID, name: 'View 1', view_config: CONFIG }),
      );
      assertEquals(response.status, 500);
    } finally {
      countErrorMock.restore();
    }
  });
});
